version: '3'
services:
    postgres:
        image: postgres
        container_name: postgresdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=senhadb
        ports:
            - "5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks: 
            - cake-network

    cake-php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: cake-php
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        networks: 
            - cake-network
        depends_on:
            - "postgres"
networks: 
    cake-network:
        driver: bridge
volumes:
    db-data:
        external: false