version: '3.7'
services:
    postgres:
        image: postgres
        container_name: postgresdb
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=senhadb
        volumes:
            - ./db-data:/var/lib/postgresql/data
        networks: 
            - cake-network
        ports:
            - "5432"


    cake-php:
        image: webdevops/php-apache:7.3
        container_name: cake-php
        volumes:
            - ./app
        networks: 
            - cake-network
        ports:
            - "8080:80"
        depends_on:
            - "postgres"
networks: 
    cake-network:
        driver: bridge
